/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppReviewRouteImport } from './routes/app.review'
import { Route as AppListingsRouteImport } from './routes/app.listings'
import { Route as AppArtisansRouteImport } from './routes/app.artisans'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAgentsRouteImport } from './routes/app.agents'
import { Route as AppReviewIdRouteImport } from './routes/app.review.$id'
import { Route as AppCatalogIdRouteImport } from './routes/app.catalog.$id'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppListingsRoute = AppListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AppRoute,
} as any)
const AppArtisansRoute = AppArtisansRouteImport.update({
  id: '/artisans',
  path: '/artisans',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewIdRoute = AppReviewIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppReviewRoute,
} as any)
const AppCatalogIdRoute = AppCatalogIdRouteImport.update({
  id: '/catalog/$id',
  path: '/catalog/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/agents': typeof AppAgentsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/artisans': typeof AppArtisansRoute
  '/app/listings': typeof AppListingsRoute
  '/app/review': typeof AppReviewRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/catalog/$id': typeof AppCatalogIdRoute
  '/app/review/$id': typeof AppReviewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/artisans': typeof AppArtisansRoute
  '/app/listings': typeof AppListingsRoute
  '/app/review': typeof AppReviewRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/catalog/$id': typeof AppCatalogIdRoute
  '/app/review/$id': typeof AppReviewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/agents': typeof AppAgentsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/artisans': typeof AppArtisansRoute
  '/app/listings': typeof AppListingsRoute
  '/app/review': typeof AppReviewRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/catalog/$id': typeof AppCatalogIdRoute
  '/app/review/$id': typeof AppReviewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/agents'
    | '/app/analytics'
    | '/app/artisans'
    | '/app/listings'
    | '/app/review'
    | '/app/'
    | '/app/catalog/$id'
    | '/app/review/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/agents'
    | '/app/analytics'
    | '/app/artisans'
    | '/app/listings'
    | '/app/review'
    | '/app'
    | '/app/catalog/$id'
    | '/app/review/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/agents'
    | '/app/analytics'
    | '/app/artisans'
    | '/app/listings'
    | '/app/review'
    | '/app/'
    | '/app/catalog/$id'
    | '/app/review/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/review': {
      id: '/app/review'
      path: '/review'
      fullPath: '/app/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/listings': {
      id: '/app/listings'
      path: '/listings'
      fullPath: '/app/listings'
      preLoaderRoute: typeof AppListingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/artisans': {
      id: '/app/artisans'
      path: '/artisans'
      fullPath: '/app/artisans'
      preLoaderRoute: typeof AppArtisansRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agents': {
      id: '/app/agents'
      path: '/agents'
      fullPath: '/app/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/review/$id': {
      id: '/app/review/$id'
      path: '/$id'
      fullPath: '/app/review/$id'
      preLoaderRoute: typeof AppReviewIdRouteImport
      parentRoute: typeof AppReviewRoute
    }
    '/app/catalog/$id': {
      id: '/app/catalog/$id'
      path: '/catalog/$id'
      fullPath: '/app/catalog/$id'
      preLoaderRoute: typeof AppCatalogIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppReviewRouteChildren {
  AppReviewIdRoute: typeof AppReviewIdRoute
}

const AppReviewRouteChildren: AppReviewRouteChildren = {
  AppReviewIdRoute: AppReviewIdRoute,
}

const AppReviewRouteWithChildren = AppReviewRoute._addFileChildren(
  AppReviewRouteChildren,
)

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppArtisansRoute: typeof AppArtisansRoute
  AppListingsRoute: typeof AppListingsRoute
  AppReviewRoute: typeof AppReviewRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppCatalogIdRoute: typeof AppCatalogIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppArtisansRoute: AppArtisansRoute,
  AppListingsRoute: AppListingsRoute,
  AppReviewRoute: AppReviewRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppCatalogIdRoute: AppCatalogIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
