"""add user description and extraction confidence to products

Revision ID: 0003_add_description_confidence
Revises: 0002_add_audit_event_updated_at
Create Date: 2026-05-08 10:00:00.000000

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0003_add_description_confidence"
down_revision = "0002_add_audit_event_updated_at"
branch_labels = None
depends_on = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column(
		"products",
		sa.Column("user_provided_description", sa.Text(), nullable=True),
	)
	op.add_column(
		"products",
		sa.Column("extraction_confidence", sa.Float(), nullable=False, server_default="0.0"),
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column("products", "extraction_confidence")
	op.drop_column("products", "user_provided_description")
	# ### end Alembic commands ###
