"""add workflow_runs table

Revision ID: 0004_add_workflow_runs
Revises: 0003_add_description_confidence
Create Date: 2026-05-11 00:00:00.000000

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0004_add_workflow_runs"
down_revision = "0003_add_description_confidence"
branch_labels = None
depends_on = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"workflow_runs",
		sa.Column("workflow_id", sa.String(length=64), primary_key=True),
		sa.Column("status", sa.String(length=32), nullable=False, server_default="pending"),
		sa.Column("current_node", sa.String(length=64), nullable=False, server_default="ingestion"),
		sa.Column("human_gate_status", sa.String(length=32), nullable=False, server_default="open"),
		sa.Column("contact_number", sa.String(length=64), nullable=True),
		sa.Column("product_id", sa.String(length=64), nullable=True),
		sa.Column("state_json", sa.JSON(), nullable=False),
		sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
		sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table("workflow_runs")
	# ### end Alembic commands ###
