"""add image_url_enhanced to products

Revision ID: 0005_add_image_url_enhanced
Revises: 0004_add_workflow_runs
Create Date: 2026-05-11 00:00:00.000000

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0005_add_image_url_enhanced"
down_revision = "0004_add_workflow_runs"
branch_labels = None
depends_on = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column(
		"products",
		sa.Column("image_url_enhanced", sa.String(length=512), nullable=True),
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column("products", "image_url_enhanced")
	# ### end Alembic commands ###
