"""add conversation_sessions table

Revision ID: 0006_add_conversation_sessions
Revises: 0005_add_image_url_enhanced
Create Date: 2026-05-11 00:00:00.000000

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0006_add_conversation_sessions"
down_revision = "0005_add_image_url_enhanced"
branch_labels = None
depends_on = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"conversation_sessions",
		sa.Column("phone_number", sa.String(length=64), primary_key=True),
		sa.Column("language", sa.String(length=16), nullable=False, server_default="english"),
		sa.Column("pending_action", sa.String(length=64), nullable=True),
		sa.Column("product_id", sa.UUID(), sa.ForeignKey("products.id"), nullable=True),
		sa.Column("state_json", sa.JSON(), nullable=False, server_default="{}"),
		sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
		sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table("conversation_sessions")
	# ### end Alembic commands ###
